---
- name: Rebuild initramfs
  ansible.builtin.command: update-initramfs -u {{ pve_nvidia_passthrough_initramfs_update_options }}

- name: Reboot to load drivers
  ansible.builtin.reboot:

- name: Restart docker service
  ansible.builtin.service:
    name: docker
    state: restarted
